module.exports = "The DK2 VR Headset is a quality piece of hardware made from good solid quality plastics." +
"DSC_0414The unit does not feel heavy, despite it’s extra 60g heft over the DK1, and on the head the weight difference is unnoticeable as the unit fits better around your face with the top strap and cable running over your head." +
"No more breakout box! Only a single, braided cable running over the top of your head." +
"1080p makes a mighty difference! Desktop sized text at 1080p is legible, particle effects pop, textures sing it’s like opening the screen-door on your virtual world (well, almost – read below)." +
"OLED and low persistence of vision produce (for the most pert) a staggeringly stable and  blur-free image when compared to the DK1′s LCD panel. Plus colours really pop, aided by those inky blacks to contrast against. Having said that, see “the bad” below for caveats." +
"DSC_0421Positional tracking ‘just works’ and is surprisingly subtle. As with many things, if something is working correctly, you shouldn’t notice it – and besides that initial ‘OMG, I can lean in and dodge’ moments, positional tracking just feels smooth and natural. Had a great time peering at the myriad retro objects found in the Technolust apartment and gazing under light fittings in Tuscany. There’s no doubt, this is a game changer for VR and when it’s not there, you really miss it." +
"The Games So, the bad news is that with the very latest SDK, released just today, installed there isn’t a huge amount of stuff you’re going to be able to play right now until more demos have been compiled against it. In fact, until you start hacking about, you’re pretty much limited to the SDK pack-in demos ‘Oculus World’ (Tuscany Lite) and the config utility’s scene. " +
"It was a delight to step back into the Tuscany Villa again, this time armed with positional tracking and a glorious 1080p OLED panel. But the DK2′s vastly improved specs show up just how basic this classic VR demo looks now. I recall my first steps with my brand new DK1 and it was a revelatory experience. Well, despite the demo’s limitations I found myself lingering to lean in and inspect branches on trees or light fittings on the wall, just because I could." +
"Video thumbnail for vimeo video Cyber-thriller Technolust launches Kickstarter, unveils new prototype (Developer Interview) - Road to Virtual RealityAfter much hacking (and some kind developer linkage) I stepped into a DK2 enabled version of Technolust and lost myself utterly! The stunning attention to detail, neon on black really lets the OLED panel shine here. In fact, this experience was the closest I think I’ve ever some to presence in virtual reality thus far. Leaning in to check the myriad retro objects, gawking at the lighting and just generally being blown away by the experience. This game was fabulous on the DK1, it’s utterly compelling now. " +
"senza preso vr mini opera oculus riftI was also lucky enough to be sent a DK2 enabled version of Senza Peso. One word, wow! Positional tracking not quite as forthright in impact as Technolust, allowed me to glance over the sides of the boat – which for some reason made me grin gormlessly. But the extra resolution, color fidelity and contrast means that the stunning visuals can really shine. And the particles, oh my, mesmerising! " +
"The lovely folk at Kite and Lightning have informed us that the DK2 enabled demo will be made available to the public in August. If you want to stay informed and grab a copy as soon as it’s available, head over to sign up here." +
"The Ugly Sorry, into each DK2 some rain must fall – and unfortunately were a fair few issues I need to be candid about." +
"The OLED panel and it’s artefacts: Darker scenes show what looks like an oddly static green haze over the image. It’s not noticable in most situations, but in the darkness of the Technolust demo it was very evident. Also, I’ve noticed a rather worrying looking smearing when high contrast areas  are in motion – the visual effect is like a cross between old fashioned LCD blur and overdriven LCD pixel trailing (evident on some early TN based 120Hz monitors). But at this stage it’s not yet clear as to the cause." +
"DSC_0422Positional tracking – place your camera carefully. Mine was placed atop my primary monitor for the duration and honestly the cameras field of view became challenged on too many occasions to keep it there. It’s quite a disconcerting feeling to lose positional tracking mid way through a head movement. I’ll probably try a below monitor placement tomorrow to see if this irons things out." +
"Low persistence of vision stutter. I noticed this during my brief demo of the Crystal Cove prototype at CES 2014 in January. During fast pans of the head, the image would stutter frquently in some demos. I suspect it’s an artefact of in consistent frame rate but it’s quite jarring to go from super smooth tracking to judder. " +
"Well! that’s it for now. We’ll be back with more detailed DK2 impressions, including full previews of games and demos as we get them working. Stay tuned!";
